name: server
description: Minimal Shelf server for practicals
version: 0.0.1
environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  mysql1: ^0.19.2
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.14.2
