name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.x'
        channel: 'stable'
        
    - name: Install dependencies
      working-directory: ./my_app
      run: flutter pub get
      
    - name: Analyze project source
      working-directory: ./my_app
      run: flutter analyze
      
    - name: Run tests
      working-directory: ./my_app
      run: flutter test
      
    - name: Build Web App
      working-directory: ./my_app
      run: flutter build web --release
